# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d371b8371dceb110f4d231023da31c3b2f3d9c5a7151c0da31f319f75123408e02932865efa0d47869172941e9428ad697a9e3f941b70aba5df6fb67fecc275a

test:
  secret_key_base: 1bb4236ea2d2c9105de059b9d284bcb18376912f8c9d888d4297ffa34f57d23ea43d5dec5e5fa8a2b70faa638cbdf04254e45c6f240ca69c62d630b226bf6fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
